# Generated by Django 3.0.5 on 2020-05-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=5, unique=True)),
                ('running', models.BooleanField(default=False)),
                ('round', models.IntegerField(default=0)),
                ('is_night', models.BooleanField(default=False)),
                ('time_length', models.IntegerField(default=True)),
                ('number_of_players', models.IntegerField(default=0)),
                ('number_of_mafia', models.IntegerField(default=0)),
                ('has_cop', models.IntegerField(default=0)),
                ('has_doctor', models.IntegerField(default=0)),
                ('has_lover', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Player', editable=False, unique=True)),
                ('is_host', models.BooleanField(default=False)),
                ('role', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Game')),
            ],
        ),
    ]
