# Generated by Django 3.0.5 on 2020-05-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='has_cop',
        ),
        migrations.RemoveField(
            model_name='game',
            name='has_doctor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='has_lover',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_mafia',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_host',
        ),
        migrations.AddField(
            model_name='player',
            name='choice',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='player',
            name='will_be_dead',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Player', editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('n', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Game')),
            ],
        ),
    ]
