# Generated by Django 3.0.5 on 2020-05-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200506_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
