# Generated by Django 3.0.5 on 2020-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200508_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
