# Generated by Django 3.0.5 on 2020-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_player_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chat',
            field=models.TextField(default=''),
        ),
    ]
