# Generated by Django 3.0.5 on 2020-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_game_mafia_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_night',
            field=models.BooleanField(default=True),
        ),
    ]
